/**
 * Nominal physical scale of the localizer images.
 *
 * Every overlay size in the app is derived from a prescription in millimetres
 * (FOV, slice thickness, gap) and drawn using this one scale, so the three
 * views of an exam always agree with each other and with the Parameters
 * panel. The value is a teaching approximation — the localizers were not
 * calibrated — and is deliberately a single constant that is easy to tune.
 *
 * This file is derived/hand-tuned; `exams.json` is generated by the pipeline
 * and must not be edited.
 */

/** Width of a full localizer image, in mm. Same value for all views of an exam. */
export const IMAGE_WIDTH_MM = 250

/**
 * Optional per-exam-family overrides, keyed by the family name shown in the
 * exam dropdown (the `exam` field in exams.json, e.g. "Brain & Orbits").
 * Leave empty to use IMAGE_WIDTH_MM everywhere.
 */
export const FAMILY_IMAGE_WIDTH_MM: Record<string, number> = {}

export function imageWidthMm(familyName: string): number {
  return FAMILY_IMAGE_WIDTH_MM[familyName] ?? IMAGE_WIDTH_MM
}
